service: serverless-stepfunctions-test

plugins:
  - serverless-step-functions

provider:
  name: aws
  region: ap-northeast-1

stepFunctions:
  stateMachines:
    ServerlessStatemachineTest:
      name: ServerlessStatemachineTest
      definition:
        StartAt: Test0
        States:
          Test0:
            Type: Task
            Resource: arn:aws:states:::lambda:invoke
            Parameters:
              FunctionName: arn:aws:lambda:ap-northeast-1:654223115725:function:StepFunctionsTest2:$LATEST
              Payload.$: "$"
            ResultPath: "$.Result"
            Next: Test1
          Test1:
            Type: Task
            Resource: arn:aws:states:::lambda:invoke
            Parameters:
              FunctionName: arn:aws:lambda:ap-northeast-1:654223115725:function:StepFunctionsTest1:$LATEST
              Payload:
                Input.$: "$"
            ResultPath: "$.Result"
            Next: Test2
          Test2:
            Type: Task
            Resource: arn:aws:states:::lambda:invoke
            Parameters:
              FunctionName: arn:aws:lambda:ap-northeast-1:654223115725:function:StepFunctionsTest2:$LATEST
              Payload:
                hoge2: FOO
                hoge1.$: "$.Result.Payload.hoge1"
            ResultPath: "$.Result"
            End: true
